### ISSUE TITLE
REQ: Show trigger time on timer 'window'.

### ISSUE THREAD

**Issue by bs27975** [i2van/hourglass#1]
Thank you for the excellent enhancements you have been making.

I have cmd scripts to quickly create timers, such as this one for every 2h:
![image](https://github.com/i2van/hourglass/assets/4133619/3adb36bb-4728-45fb-a451-cafc988ed366)

Could the 'trigger time' be shown in the lower right (or something), much like the timer title is shown just above the 'time to trigger' time display? Here, e.g. '8;30:02 pm'.

Depending upon the duration, sometimes it is more useful to know when to return to something, than knowing how long until it happens. [The program has no way to know which is which, when. Thus this request.]

**Comment by i2van** [comment]
You can specify time in the command line for the title from batch or cmd as follows (depends from your system locale):

```shell
hourglass -t "Timer 1 %DATE% %TIME:~0,8%" 10
```

`%TIME:~0,8%` takes first 8 symbols, which are `hh:mm:ss` in my locale.

![image](https://github.com/i2van/hourglass/assets/5464660/50a50389-b684-46f0-b3a6-308abd7da980)

**Comment by bs27975** [comment]
I understand that. I frequently use the desired time on the command line already. Other times the duration.

This is about _displaying_ the 'trigger time', not specifying it.

**Comment by i2van** [comment]
![image](https://github.com/i2van/hourglass/assets/5464660/395b0236-cd36-4408-92c8-2ede8d994604)

**Comment by bs27975** [comment]
Yes, that is the sort of thing I meant.

However, consider the inevitable breaking down of the display into sections:
`<Left> <Middle> <Right>` <-- Header
`<Left> <Middle> <Right>` <-- Main
`<Left> <Middle> <Right>` <-- Footer

The 'trigger' time could go in the footer-right, leaving all else as currently displayed.
[And setting the frame (work) for future ... enhancements.]

Granted / agreed, the display gets more complex when the timer is to go off after the next midnight.
Thus footer left could be 'tomorrow', 'tuesday, and so on.

I had not considered the impact of times past next midnight, beyond a date, and appreciate the idea of 'tomorrow', or 'Tuesday'. I don't envy you the design decisions you must choose.

**Comment by i2van** [comment]
Implemented in [1.15.30](https://github.com/i2van/hourglass/releases/tag/1.15.30)

The **Advanced options** / **Show trigger time** timer window context menu option shows the trigger time in the timer window and in the notification area context menu. The command-line option is `--show-trigger-time`, `-st`, `/st`
