### ISSUE TITLE
REQ:Prompt before starting next loop

### ISSUE THREAD

**Issue by jrm200306** [i2van/hourglass#12]
Please add a option 
prompt on timer expire to confirm start or not the next loop.

**Comment by i2van** [comment]
Could you help me understand how it should work?

1. Timer expires.
2. Show **Would you like to restart timer?** notification **only** if **restart notification option** is set and **Pop up when expired** option enabled. Do not show this notification if **Pop up when expired** option is not enabled.

**Comment by jrm200306** [comment]
@i2van 
Yes,your post is like what I want.
It use to break work sometimes for any reason
example:
2 hr work(1st loop completed) ->  45 min launch time(break) -> 2 hr work (2nd  loop completed) -> 15 min (break)
I want the loop only restart when i comfirm

**Comment by i2van** [comment]
> @i2van Yes,your post is like what I want. It use to break work sometimes for any reason example: 2 hr work(1st loop completed) -> 45 min launch time(break) -> 2 hr work (2nd loop completed) -> 15 min (break) I want the loop only restart when i comfirm

What about adding option for pausing loop timer automatically when expired (it will be applied for newly created timers also if set)? It removes dialog boxes twiddling.

**Comment by jrm200306** [comment]
> > @i2van Yes,your post is like what I want. It use to break work sometimes for any reason example: 2 hr work(1st loop completed) -> 45 min launch time(break) -> 2 hr work (2nd loop completed) -> 15 min (break) I want the loop only restart when i comfirm
> 
> What about adding option for pausing loop timer automatically when expired (it will be applied for newly created timers also if set)? It removes dialog boxes twiddling.

Yes,and make a global hotkey to start the timer will be great

**Comment by i2van** [comment]
@jrm200306 You can get latest build [here](https://github.com/i2van/hourglass/actions/runs/10522682852)

![image](https://github.com/user-attachments/assets/c23eea94-13db-42ae-974b-e7da65c6486a)

**Comment by i2van** [comment]
@jrm200306 Any comments are appreciated: https://github.com/i2van/hourglass/issues/14

**Comment by i2van** [comment]
Implemented in [1.15.33](https://github.com/i2van/hourglass/releases/tag/1.15.33)

![image](https://github.com/user-attachments/assets/bdd8f5a3-e4f1-46fb-abc8-55dd9411d9c9)
