### ISSUE TITLE
Windows 11 Accent Colors for Themes

### ISSUE THREAD

**Issue by hl2guide** [i2van/hourglass#13]
Please consider adding Windows 11 Accent Colors to the Themes in Hourglass.

e.g.

![colors](https://github.com/user-attachments/assets/64ef2a4c-a066-4340-aeb7-0c974cd23188)

may be a "use Windows accent color" option would be nice too.

**Comment by i2van** [comment]
Could you elaborate how it should work?

**Comment by hl2guide** [comment]
The default colors that Hourglass uses for progress bars don't match Windows 11 colors.

I would set the program to use the exact same themes as it currently has,
and then if the PC is running Windows 11 it readjusts the progress bar color to suit Windows 11 colors (palette above).

**Comment by i2van** [comment]
@hl2guide You can get build [here](https://github.com/i2van/hourglass/actions/runs/10632461660).

Dynamic update of accent color is not supported (and might not be supported).
