### ISSUE TITLE
stopwatch feature

### ISSUE THREAD

**Issue by hl2guide** [i2van/hourglass#15]
Please add a stopwatch feature if it is not implemented yet.

**Comment by i2van** [comment]
Could you elaborate? I don't think this feature is feasible for app at all...

**Comment by hl2guide** [comment]
> Could you elaborate? I don't think this feature is feasible for app at all...

most timer apps I've tried have this feature but if you're not keen that's fine 👍.

**Comment by i2van** [comment]
You can display elapsed time instead of time left:

Options > Advanced options > Show elapsed time instead of time left

This option is a second from the top.
