### ISSUE TITLE
Clarify Ngen Support for Installer

### ISSUE THREAD

**Issue by hl2guide** [i2van/hourglass#19]
The installer option (HourglassInstaller.exe) seems to auto generate native images (using Ngen). Is this correct?

**Comment by i2van** [comment]
Yes. I think it as implemented in original installer. You can verify it using [Process Explorer](https://learn.microsoft.com/en-us/sysinternals/downloads/process-explorer):

![image](https://github.com/user-attachments/assets/05d91750-f4c7-4b34-b790-eab18ee90a98)
