### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by Perverance** [i2van/hourglass#5]
Hi! Thank you for your effort on improving the app!

I was wondering, how could I build it from source without using Visual Studio IDE?

**Comment by i2van** [comment]
Thank you!

Build steps can be found at [build.yml](https://github.com/i2van/hourglass/blob/develop/.github/workflows/build.yml) GitHub workflow file.

Please take a look at any GitHub workflow output [here](https://github.com/i2van/hourglass/actions/runs) for understanding how it works.

Exact build steps are:

```
dotnet restore Hourglass.Test\Hourglass.Test.csproj
msbuild /p:Configuration="Release Portable" Hourglass.sln
msbuild /p:Configuration="Release" Hourglass.sln
```

MSBuild should be [installed separately](https://stackoverflow.com/a/44398715) ([direct download link](https://aka.ms/vs/17/release/vs_BuildTools.exe)).

**Comment by Perverance** [comment]
> Thank you!
> 
> Build steps can be found at [build.yml](https://github.com/i2van/hourglass/blob/develop/.github/workflows/build.yml) GitHub workflow file.
> 
> Please take a look at any GitHub workflow output [here](https://github.com/i2van/hourglass/actions) for understanding how it works.
> 
> Exact build steps are (**Windows only**):
> 
> ```
> dotnet restore Hourglass.Test\Hourglass.Test.csproj
> msbuild /p:Configuration="Release Portable" Hourglass.sln
> msbuild /p:Configuration="Release" Hourglass.sln
> ```
> 
> where
> 
>     * [dotnet](https://learn.microsoft.com/en-us/dotnet/core/tools/) is a part of .NET SDK
> 
>     * MSBuild is [installed separately](https://stackoverflow.com/a/44398715) ([direct download link](https://aka.ms/vs/17/release/vs_BuildTools.exe)).
> 
>     * [WiX Toolset build tools](https://wixtoolset.org/docs/wix3/) are required for the `Release` build

Thank you so much for the dedicated response! I appreciate it :)

**Comment by i2van** [comment]
> [!MPORTANT]
> There is a [bug](https://github.com/dotnet/wpf/issues/9582) in VS Preview, [workaround](https://github.com/dotnet/wpf/issues/9582#issuecomment-2295640074).
