### ISSUE TITLE
Not clear how to save timers, add to context menu?

### ISSUE THREAD

**Issue by petervk** [i2van/hourglass#6]
I'm not sure if I'm just dense but I don't see any way to save timers aside from guessing that the keyboard shortcut is "Ctrl-S". Can this be added to the context menu?

**Comment by i2van** [comment]
`Ctrl+S` stops timer. Hourglass saves closed/stopped timers. I didn't changed this logic and I probably won't add nothing to it.

**Comment by i2van** [comment]
See [Hourglass FAQ](https://chris.dziemborowicz.com/apps/hourglass/#faq)
